/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.irisdemo.banksim.avroevent;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransferEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8456902496112058591L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransferEvent\",\"namespace\":\"com.irisdemo.banksim.avroevent\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"eventDate\",\"type\":\"string\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"transferType\",\"type\":\"string\"},{\"name\":\"senderAccount\",\"type\":\"string\"},{\"name\":\"receivingAccount\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransferEvent> ENCODER =
      new BinaryMessageEncoder<TransferEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransferEvent> DECODER =
      new BinaryMessageDecoder<TransferEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransferEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransferEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransferEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TransferEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransferEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransferEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransferEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransferEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public java.lang.CharSequence eventDate;
  @Deprecated public java.lang.CharSequence transferType;
  @Deprecated public java.lang.CharSequence senderAccount;
  @Deprecated public java.lang.CharSequence receivingAccount;
  @Deprecated public double amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransferEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param eventDate The new value for eventDate
   * @param transferType The new value for transferType
   * @param senderAccount The new value for senderAccount
   * @param receivingAccount The new value for receivingAccount
   * @param amount The new value for amount
   */
  public TransferEvent(java.lang.Long id, java.lang.CharSequence eventDate, java.lang.CharSequence transferType, java.lang.CharSequence senderAccount, java.lang.CharSequence receivingAccount, java.lang.Double amount) {
    this.id = id;
    this.eventDate = eventDate;
    this.transferType = transferType;
    this.senderAccount = senderAccount;
    this.receivingAccount = receivingAccount;
    this.amount = amount;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return eventDate;
    case 2: return transferType;
    case 3: return senderAccount;
    case 4: return receivingAccount;
    case 5: return amount;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: eventDate = (java.lang.CharSequence)value$; break;
    case 2: transferType = (java.lang.CharSequence)value$; break;
    case 3: senderAccount = (java.lang.CharSequence)value$; break;
    case 4: receivingAccount = (java.lang.CharSequence)value$; break;
    case 5: amount = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'eventDate' field.
   * @return The value of the 'eventDate' field.
   */
  public java.lang.CharSequence getEventDate() {
    return eventDate;
  }


  /**
   * Sets the value of the 'eventDate' field.
   * @param value the value to set.
   */
  public void setEventDate(java.lang.CharSequence value) {
    this.eventDate = value;
  }

  /**
   * Gets the value of the 'transferType' field.
   * @return The value of the 'transferType' field.
   */
  public java.lang.CharSequence getTransferType() {
    return transferType;
  }


  /**
   * Sets the value of the 'transferType' field.
   * @param value the value to set.
   */
  public void setTransferType(java.lang.CharSequence value) {
    this.transferType = value;
  }

  /**
   * Gets the value of the 'senderAccount' field.
   * @return The value of the 'senderAccount' field.
   */
  public java.lang.CharSequence getSenderAccount() {
    return senderAccount;
  }


  /**
   * Sets the value of the 'senderAccount' field.
   * @param value the value to set.
   */
  public void setSenderAccount(java.lang.CharSequence value) {
    this.senderAccount = value;
  }

  /**
   * Gets the value of the 'receivingAccount' field.
   * @return The value of the 'receivingAccount' field.
   */
  public java.lang.CharSequence getReceivingAccount() {
    return receivingAccount;
  }


  /**
   * Sets the value of the 'receivingAccount' field.
   * @param value the value to set.
   */
  public void setReceivingAccount(java.lang.CharSequence value) {
    this.receivingAccount = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Creates a new TransferEvent RecordBuilder.
   * @return A new TransferEvent RecordBuilder
   */
  public static com.irisdemo.banksim.avroevent.TransferEvent.Builder newBuilder() {
    return new com.irisdemo.banksim.avroevent.TransferEvent.Builder();
  }

  /**
   * Creates a new TransferEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransferEvent RecordBuilder
   */
  public static com.irisdemo.banksim.avroevent.TransferEvent.Builder newBuilder(com.irisdemo.banksim.avroevent.TransferEvent.Builder other) {
    if (other == null) {
      return new com.irisdemo.banksim.avroevent.TransferEvent.Builder();
    } else {
      return new com.irisdemo.banksim.avroevent.TransferEvent.Builder(other);
    }
  }

  /**
   * Creates a new TransferEvent RecordBuilder by copying an existing TransferEvent instance.
   * @param other The existing instance to copy.
   * @return A new TransferEvent RecordBuilder
   */
  public static com.irisdemo.banksim.avroevent.TransferEvent.Builder newBuilder(com.irisdemo.banksim.avroevent.TransferEvent other) {
    if (other == null) {
      return new com.irisdemo.banksim.avroevent.TransferEvent.Builder();
    } else {
      return new com.irisdemo.banksim.avroevent.TransferEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransferEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransferEvent>
    implements org.apache.avro.data.RecordBuilder<TransferEvent> {

    private long id;
    private java.lang.CharSequence eventDate;
    private java.lang.CharSequence transferType;
    private java.lang.CharSequence senderAccount;
    private java.lang.CharSequence receivingAccount;
    private double amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.irisdemo.banksim.avroevent.TransferEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventDate)) {
        this.eventDate = data().deepCopy(fields()[1].schema(), other.eventDate);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.transferType)) {
        this.transferType = data().deepCopy(fields()[2].schema(), other.transferType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.senderAccount)) {
        this.senderAccount = data().deepCopy(fields()[3].schema(), other.senderAccount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.receivingAccount)) {
        this.receivingAccount = data().deepCopy(fields()[4].schema(), other.receivingAccount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.amount)) {
        this.amount = data().deepCopy(fields()[5].schema(), other.amount);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing TransferEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.irisdemo.banksim.avroevent.TransferEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventDate)) {
        this.eventDate = data().deepCopy(fields()[1].schema(), other.eventDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.transferType)) {
        this.transferType = data().deepCopy(fields()[2].schema(), other.transferType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.senderAccount)) {
        this.senderAccount = data().deepCopy(fields()[3].schema(), other.senderAccount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.receivingAccount)) {
        this.receivingAccount = data().deepCopy(fields()[4].schema(), other.receivingAccount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.amount)) {
        this.amount = data().deepCopy(fields()[5].schema(), other.amount);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventDate() {
      return eventDate;
    }


    /**
      * Sets the value of the 'eventDate' field.
      * @param value The value of 'eventDate'.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder setEventDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.eventDate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventDate' field has been set.
      * @return True if the 'eventDate' field has been set, false otherwise.
      */
    public boolean hasEventDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventDate' field.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder clearEventDate() {
      eventDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'transferType' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransferType() {
      return transferType;
    }


    /**
      * Sets the value of the 'transferType' field.
      * @param value The value of 'transferType'.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder setTransferType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.transferType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'transferType' field has been set.
      * @return True if the 'transferType' field has been set, false otherwise.
      */
    public boolean hasTransferType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'transferType' field.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder clearTransferType() {
      transferType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'senderAccount' field.
      * @return The value.
      */
    public java.lang.CharSequence getSenderAccount() {
      return senderAccount;
    }


    /**
      * Sets the value of the 'senderAccount' field.
      * @param value The value of 'senderAccount'.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder setSenderAccount(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.senderAccount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'senderAccount' field has been set.
      * @return True if the 'senderAccount' field has been set, false otherwise.
      */
    public boolean hasSenderAccount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'senderAccount' field.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder clearSenderAccount() {
      senderAccount = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'receivingAccount' field.
      * @return The value.
      */
    public java.lang.CharSequence getReceivingAccount() {
      return receivingAccount;
    }


    /**
      * Sets the value of the 'receivingAccount' field.
      * @param value The value of 'receivingAccount'.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder setReceivingAccount(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.receivingAccount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'receivingAccount' field has been set.
      * @return True if the 'receivingAccount' field has been set, false otherwise.
      */
    public boolean hasReceivingAccount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'receivingAccount' field.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder clearReceivingAccount() {
      receivingAccount = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder setAmount(double value) {
      validate(fields()[5], value);
      this.amount = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.irisdemo.banksim.avroevent.TransferEvent.Builder clearAmount() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransferEvent build() {
      try {
        TransferEvent record = new TransferEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.eventDate = fieldSetFlags()[1] ? this.eventDate : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.transferType = fieldSetFlags()[2] ? this.transferType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.senderAccount = fieldSetFlags()[3] ? this.senderAccount : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.receivingAccount = fieldSetFlags()[4] ? this.receivingAccount : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.amount = fieldSetFlags()[5] ? this.amount : (java.lang.Double) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransferEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransferEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransferEvent>
    READER$ = (org.apache.avro.io.DatumReader<TransferEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.eventDate);

    out.writeString(this.transferType);

    out.writeString(this.senderAccount);

    out.writeString(this.receivingAccount);

    out.writeDouble(this.amount);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.eventDate = in.readString(this.eventDate instanceof Utf8 ? (Utf8)this.eventDate : null);

      this.transferType = in.readString(this.transferType instanceof Utf8 ? (Utf8)this.transferType : null);

      this.senderAccount = in.readString(this.senderAccount instanceof Utf8 ? (Utf8)this.senderAccount : null);

      this.receivingAccount = in.readString(this.receivingAccount instanceof Utf8 ? (Utf8)this.receivingAccount : null);

      this.amount = in.readDouble();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.eventDate = in.readString(this.eventDate instanceof Utf8 ? (Utf8)this.eventDate : null);
          break;

        case 2:
          this.transferType = in.readString(this.transferType instanceof Utf8 ? (Utf8)this.transferType : null);
          break;

        case 3:
          this.senderAccount = in.readString(this.senderAccount instanceof Utf8 ? (Utf8)this.senderAccount : null);
          break;

        case 4:
          this.receivingAccount = in.readString(this.receivingAccount instanceof Utf8 ? (Utf8)this.receivingAccount : null);
          break;

        case 5:
          this.amount = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










